name: CI

on: [push, pull_request]

env:
  API_BASE_URL=https://eatgo-customer-api.ahastudio.com

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
        env:
          HEADLESS: true
      - name: Lint
        run: npm run lint
